# Usar una imagen base de Python
FROM python:3.9-slim

# Instalar DIG
RUN apt-get update && apt-get install -y dnsutils

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de requerimientos y la aplicación
COPY requirements.txt requirements.txt
COPY resolver.py resolver.py

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Comando para correr el resolver
CMD ["python", "resolver.py"]

